language: python
python:
  - "3.6"
install:
  - pip install pytest pycodestyle pyflakes vulture
script:
  - cd tsp
  - pyflakes .
  - pycodestyle --max-line-length=120 .
  - vulture --min-confidence=100 .
  - python3 -m pytest tests/
